name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: make
    - name: test
      run: |
      make check &> test_out.txt
      git --no-pager diff --exit-code HEAD
#    - name: make distcheck
#      run: make distcheck
